name: Renovate Dashboard

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:     # allow manual trigger

env:
  LOG_LEVEL: debug

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.12
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: latest
